### PR TITLE
Misc Updates (fix links, update gems)

### PR DESCRIPTION
**Pull request by jeremiahlukus**
This is a 🐞 bug fix. 

- [ ] I've added tests (if it's a bug, feature or enhancement)
- [ ] I've adjusted the documentation (if it's a feature or enhancement)
- [ ] The test suite passes (run `bundle exec rspec` to verify this)

## Summary
When running jets new and adding pg i noticed it was adding an older version of pg and then failing. 
I also updated mysql and other active and action gems

### CODE REVIEW

**Comment by jeremiahlukus** [comment]
When running the tests i get 575 examples, 4 failures on master and my branch.

**Comment by jeremiahlukus** [comment]
Getting one last failure, i think its my local env? I have python installed so not sure what is going on, but i fixed the other broken tests and a code error 
https://github.com/boltops-tools/jets/pull/663/files#diff-1ae1c5b5589ea49f6177ae44cad8270e9bf0d437827208175abbcdc279c76f86R55
that was breaking a test.  Let me know if you need anything else @tongueroo 

```
Failures:

  1) Jets::PolyFun python successful command produces lambda response payload
     Failure/Error: raise_error(resp)
     
     Jets::PolyFun::PythonError:
       sh: python: command not found
     # ./lib/jets/poly_fun.rb:21:in `run'
     # ./spec/lib/jets/poly_fun_spec.rb:9:in `block (4 levels) in <top (required)>'

Finished in 23.62 seconds (files took 2.93 seconds to load)
575 examples, 1 failure

Failed examples:

rspec ./spec/lib/jets/poly_fun_spec.rb:8 # Jets::PolyFun python successful command produces lambda response payload
```

**Comment by jeremiahlukus** [comment]
Somehow this PR breaks csrf_meta_tags.
Screenshot 2023-09-12 at 11 48 03 AM

**Comment by tongueroo** [comment]
It's related to the changes from rails 6 to rails 7. Going to leave the issue closed and focus on jets v5 instead, where this has been fixed. Wanted to at least explain it though.

**Pull request closed without merging**
